#!/bin/bash
#set -v -x	

if [ ! -d "$HOME"/_output/ ]; then
	mkdir "$HOME"/_output
fi

while getopts ":i:a:" opt; do
	case $opt in
		i)
			echo "adding $0 to bashrc as \"makegif\""
			sdir=$(readlink -f "$0")
			echo "alias makegif='$sdir'" >> ~/.bashrc
			echo "Installing mtn"
			if [ ! -f ~/.mtn/mtn ]; then
			mkdir ~/.mtn
			cd ~/.mtn
			wget -O mtn.tgz http://sourceforge.net/projects/moviethumbnail/files/movie%20thumbnailer%20linux%20binary/mtn-200808a-linux/mtn-200808a-linux.tgz/download
			tar xzf mtn.tgz
			mv mtn-*/mtn .
			chmod +x mtn
			rm -rf mtn-* mtn.tgz
			wget -O font.tar.gz https://releases.pagure.org/liberation-fonts/liberation-fonts-ttf-2.00.1.tar.gz
			tar xzf font.tar.gz
			mv liberation-*/*.ttf .
			rm -rf liberation-*/
			else
			echo "mtn was found at ~/.mtn/mtn"
			fi
			
			echo "Isntalling python3"
			if command -v python3.6 2>/dev/null 
				then
					echo "python3.6 is already installed"
				else 
					wget https://www.python.org/ftp/python/3.6.2/Python-3.6.2.tar.xz && \
					tar xJf ./Python-3.6.2.tar.xz && \
					cd ./Python-3.6.2 && \
					./configure --prefix=$HOME && make && make install 
					# Configure environment
					grep -q "export PATH" ~/.bashrc
					if [[ $? -eq 1 ]]; then
						echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
					else
						grep 'export PATH' ~/.bashrc | grep -q '$HOME'
						if [[ $? -eq 1 ]]; then
							sed -i -e 's/PATH=/PATH=$HOME\/bin:/g' ~/.bashrc
						fi
					fi
					# Cleanup
				cd ..
				rm -rf ./Python-3.6.2
				rm -f ./Python-3.6.2.tar.xz
			fi
			echo "Installing emptorrentify"
			wget https://server428.seedhost.eu/alucard/upping/emptorrentify.zip && \
			unzip emptorrentify.zip && \
			mv emptorrentify/* ~/bin/ && \
			rm -rf emptorrentify && \
			rm -f emptorrentify.zip
			grep -q emptorrentify ~/.bashrc
			if [[ $? -eq 1 ]]; then
				echo alias emptorrent=\'~/usr/local/lib/python3.4 ~/lib/emptorrentify.py\' >> ~/.bashrc
			fi
			read -p "Please input your announce key and hit return: " key
			sed -i -e "s/\/announce/\/$key\/announce/g" ~/bin/py3createemptorrent.py
			sed -i -e "s/\/announce/\/$key\/announce/g" ~/bin/py3createtorrent.py
			
			echo "alias mtns='mkdir -p Screens && ~/.mtn/mtn -n -w 1600 -c 4 -D 6 -b 0.6 -r 6 -j 95 -k 00008b -F FFFFFF:12 -f ~/.mtn/DroidSans-Bold.ttf -O Screens'" >> ~/.bashrc
			echo "alias mtnf='mkdir -p Screens && ~/.mtn/mtn -n -I -w 0 -c 1 -j 95 -D 12 -f ~/.mtn/DroidSans-Bold.ttf -O Screens'" >> ~/.bashrc
			echo "alias mtnq='mkdir -p Screens && ~/.mtn/mtn -f ~/.mtn/DroidSans-Bold.ttf -n -s 10 -c 3 -D 6 -b 0.6 -h 100 -r 15 -w 1600 -D7 -b 1 -L 4:1 -j 90 -k 00008b -F FFFFFF:12 -o -empblue.jpg -O Screens'" >> ~/.bashrc
			echo "Done with install"
			exit
			;;
		 a)
     		echo "Making torrent"
			~/bin/python3.6 /home/owner/bin/emptorrentify.py
			echo "Done with Torrent"
			curdir=$(pwd)
			echo "Making Screens"
	  		~/.mtn/mtn -f ~/.mtn/DroidSans-Bold.ttf -n -s 10 -c 3 -D 6 -b 0.6 -h 100 -r 15 -w 1600 -L 4:1 -j 90 -k 00008b -F FFFFFF:12 -o -empblue.jpg -O "$HOME"/_output/ "$3"
	  		echo "Done with Screens"
	  		echo "-a was triggered, Parameter: $OPTARG" >&2
	  		time=$OPTARG
	  		echo "Making Gifs"
	  		name=$(basename "$3")
	  		mkdir /tmp/grabs2
	  		ffmpeg -v error -ss "$time" -t 2 -i "$3" -r 15 -vf "scale=400:-1" /tmp/grabs2/out%03d.png
	  		ffmpeg -v error -i /tmp/grabs2/out%3d.png -vf palettegen /tmp/grabs2/palette.png
	  		ffmpeg -v error -r 15 -i /tmp/grabs2/out%3d.png -i /tmp/grabs2/palette.png -filter_complex paletteuse=floyd_steinberg -loop 0 "$name".gif	  
      		rm -rf /tmp/grabs2
	  		echo "Done"
	  		echo "Making text file"
	  		mediainfo "$3" >> $3info.txt
	  		;;
		\?)
			echo "Invalid option: -"$OPTARG""
			exit
			;;
	esac
done






if [ -z "$time" ]; then
	echo "Making torrent"
	~/bin/python3.6 /home/owner/bin/emptorrentify.py
	echo "Done with Torrent"
	curdir=$(pwd)
	echo "Making Screens"
	~/.mtn/mtn -f ~/.mtn/DroidSans-Bold.ttf -n -s 10 -c 3 -D 6 -b 0.6 -h 100 -r 15 -w 1600 -L 4:1 -j 90 -k 00008b -F FFFFFF:12 -o -O "$HOME"/_output/ -empblue.jpg "$1"
	echo "Done with Screens"
	echo "Making text file"
	mediainfo "$1" >> $1info.txt
	echo "Done"
fi

echo "Moving Files"
mv "$curdir"/*.torrent "$HOME"/_output/
mv "$curdir"/*.gif "$HOME"/_output/
echo "Done with moving files"
